[package]
name = "bencher"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[profile.release]
panic = "abort"
debug = true

[dependencies]
dashmap = { path = ".." }
bustle = "0.4.1"
fxhash = "0.2.1"
num_cpus = "1.12.0"
tracing-subscriber = "0.2.3"
